<a href="https://colab.research.google.com/github/NISHANTSRI/Machine-Learning/blob/main/logistic_regression_minor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/content/indian_liver_patient (1).csv")

In [3]:
data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [4]:
data['Gender'] = np.where(data['Gender'] == 'Male', 0, data['Gender'])
data['Gender'] = np.where(data['Gender'] == 'Female', 1, data['Gender'])

In [5]:
data.head()

Age Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65      1              0.7               0.1                   187   
1   62      0             10.9               5.5                   699   
2   62      0              7.3               4.1                   490   
3   58      0              1.0               0.4                   182   
4   72      0              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [8]:
data = data.dropna()

In [9]:
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [10]:
data.head()

Age Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65      1              0.7               0.1                   187   
1   62      0             10.9               5.5                   699   
2   62      0              7.3               4.1                   490   
3   58      0              1.0               0.4                   182   
4   72      0              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [14]:
X = data.iloc[:,:-1].values
print(X)

[[65 1 0.7 ... 6.8 3.3 0.9]
 [62 0 10.9 ... 7.5 3.2 0.74]
 [62 0 7.3 ... 7.0 3.3 0.89]
 ...
 [52 0 0.8 ... 6.4 3.2 1.0]
 [31 0 1.3 ... 6.8 3.4 1.0]
 [38 0 1.0 ... 7.3 4.4 1.5]]


In [15]:
y = data.iloc[:,-1].values
print(y)

[1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 2 1 2 1 1 1 1 1 1 2 1 1 1 2 2 1 1 2 2 2 1 2
 1 1 1 1 2 2 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1
 1 2 1 1 2 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 2 1 2 2 2 2 2 2
 1 2 1 2 2 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1
 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1
 2 1 1 1 2 1 1 1 2 2 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 1 2 1 1 2 2 1 2 1 1 1 1
 2 1 1 1 1 2 1 2 1 1 1 1 1 2 1 2 1 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 2 1 1 1
 1 1 2 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 2 1 2 1 1 1 2 1 1 1 2 1 2 1 1 1 2 1
 2 2 1 1 2 1 2 1 1 1 1 1 1 2 1 2 2 1 1 2 1 1 1 2 1 2 2 2 2 2 1 1 1 2 1 1 1
 1 1 1 1 1 2 1 2 1 1 1 1 2 1 1 1 1 1 2 1 1 1 2 1 2 2 2 2 2 2 2 1 1 1 2 1 2
 2 1 1 2 1 2 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 2 1 1 2 1 1 1 1
 2 1 2 2 1 1 2 1 1 1 2 1 2 1 1 2 1 2 1 1 2 1 2 2 2 1 1 1 1 1 1 1 1 2 2 1 1
 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 2 2 2 2 2 1 1 1 1 2 1 1 2 1
 1 1 1 2 2 1 2 1 2 1 2 1 

In [17]:
X.shape

(579, 10)

In [18]:
y.shape

(579,)

In [19]:
amino = StandardScaler()

In [41]:
X = amino.fit_transform(X)

In [42]:
print(X )

[[ 1.24740264  1.77079482 -0.42031984 ...  0.29372174  0.20344649
  -0.14738974]
 [ 1.06230624 -0.56471817  1.21893587 ...  0.93965456  0.07746198
  -0.64846078]
 [ 1.06230624 -0.56471817  0.64037503 ...  0.47827397  0.20344649
  -0.17870668]
 ...
 [ 0.44531827 -0.56471817 -0.40424871 ... -0.07538274  0.07746198
   0.16577966]
 [-0.85035649 -0.56471817 -0.32389304 ...  0.29372174  0.329431
   0.16577966]
 [-0.4184649  -0.56471817 -0.37210644 ...  0.75510233  1.5892761
   1.73162664]]


In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.15,random_state = 11)

In [45]:
print(X_train)

[[-1.15885048 -0.56471817 -0.21139509 ...  1.21648291  1.46329159
   0.79211845]
 [ 1.30910143 -0.56471817  1.90999465 ...  0.01689338 -1.18238312
  -1.71323673]
 [-1.22054927  1.77079482 -0.38817757 ...  0.38599785  1.5892761
   2.35796544]
 ...
 [-0.5418625   1.77079482 -0.40424871 ...  0.1091695  -0.04852253
  -0.46055914]
 [ 0.93890865 -0.56471817  0.56001936 ...  0.29372174 -0.17450704
  -0.77372854]
 [ 0.81551105  1.77079482 -0.14711056 ... -1.64407674 -1.68632116
  -1.08689793]]


In [46]:
X_train.shape

(492, 10)

In [47]:
X_test.shape

(87, 10)

In [48]:
y_train.shape

(492,)

In [49]:
y_test.shape

(87,)

In [50]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 23)

In [51]:
logistic.fit(X_train,y_train)

LogisticRegression(random_state=23)

In [52]:
y_pred = logistic.predict(X_test)

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[60  2]
 [20  5]]


0.7471264367816092